"""Add human_game_cache table for fast game lookup and stats optimization

Revision ID: 007ae3e9eb49
Revises: 4545bbed2826
Create Date: 2026-02-05 00:24:02.438500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007ae3e9eb49'
down_revision = '4545bbed2826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_game_cache',
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('game_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_processed_games_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('human_id')
    )
    with op.batch_alter_table('human_game_cache', schema=None) as batch_op:
        batch_op.create_index('idx_human_game_cache_games_count', ['games_count'], unique=False)
        batch_op.create_index('idx_human_game_cache_last_updated', ['last_updated_at'], unique=False)
        batch_op.create_index('idx_human_game_cache_needs_processing', ['games_count', 'last_processed_games_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_game_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_human_game_cache_needs_processing')
        batch_op.drop_index('idx_human_game_cache_last_updated')
        batch_op.drop_index('idx_human_game_cache_games_count')

    op.drop_table('human_game_cache')
    # ### end Alembic commands ###
