"""Add org_id to Team model (nullable initially)

Revision ID: 02e745dc14a9
Revises: 5c7c11591cd5
Create Date: 2025-09-08 23:44:56.743889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e745dc14a9'
down_revision = '5c7c11591cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('teams_name_key', type_='unique')
        batch_op.create_unique_constraint('_org_team_name_uc', ['org_id', 'name'])
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_org_team_name_uc', type_='unique')
        batch_op.create_unique_constraint('teams_name_key', ['name'])
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
