"""Add aggregation timestamp tracking to all stats tables

Revision ID: 045ec377184c
Revises: 4db5c221dd97
Create Date: 2025-11-14 15:37:01.788479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045ec377184c'
down_revision = '4db5c221dd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_skater_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('level_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('level_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_skater_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('aggregation_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('level_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('level_stats_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_column('aggregation_completed_at')
        batch_op.drop_column('aggregation_started_at')

    # ### end Alembic commands ###
