"""Add team_id to GameStatsGoalie unique constraint

Revision ID: 1010723436cb
Revises: d19d57770097
Create Date: 2025-11-19 12:32:21.391548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1010723436cb'
down_revision = 'd19d57770097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.drop_constraint('_game_human_uc_goalie', type_='unique')
        batch_op.create_unique_constraint('_game_human_uc_goalie', ['game_id', 'human_id', 'team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.drop_constraint('_game_human_uc_goalie', type_='unique')
        batch_op.create_unique_constraint('_game_human_uc_goalie', ['game_id', 'human_id'])

    # ### end Alembic commands ###
