"""Add SkillValuePPGRatio table and update skill propagation logic

Revision ID: 10ca37ca3956
Revises: e81369b423bc
Create Date: 2025-01-29 20:20:46.098457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ca37ca3956'
down_revision = 'e81369b423bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_value_ppg_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_skill_value', sa.Float(), nullable=False),
    sa.Column('to_skill_value', sa.Float(), nullable=False),
    sa.Column('ppg_ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_skill_value', 'to_skill_value', name='_from_to_skill_value_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_value_ppg_ratios')
    # ### end Alembic commands ###
