"""Add per-game stats tables for RAG system

Revision ID: 13680bb09319
Revises: 045ec377184c
Create Date: 2025-11-18 19:57:12.995797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13680bb09319'
down_revision = '045ec377184c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stats_goalie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_time', sa.Time(), nullable=False),
    sa.Column('goals_allowed', sa.Integer(), nullable=False),
    sa.Column('shots_faced', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('save_percentage', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'human_id', name='_game_human_uc_goalie')
    )
    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_game_stats_goalie_human_date', ['human_id', 'game_date'], unique=False, postgresql_using='btree')
        batch_op.create_index('idx_game_stats_goalie_human_team_date', ['human_id', 'team_id', 'game_date'], unique=False, postgresql_using='btree')
        batch_op.create_index(batch_op.f('ix_game_stats_goalie_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_goalie_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_goalie_human_id'), ['human_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_goalie_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_goalie_team_id'), ['team_id'], unique=False)

    op.create_table('game_stats_skater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('game_time', sa.Time(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('penalty_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'human_id', name='_game_human_uc_skater')
    )
    with op.batch_alter_table('game_stats_skater', schema=None) as batch_op:
        batch_op.create_index('idx_game_stats_skater_human_date', ['human_id', 'game_date'], unique=False, postgresql_using='btree')
        batch_op.create_index('idx_game_stats_skater_human_team_date', ['human_id', 'team_id', 'game_date'], unique=False, postgresql_using='btree')
        batch_op.create_index(batch_op.f('ix_game_stats_skater_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_skater_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_skater_human_id'), ['human_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_skater_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_skater_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats_skater', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_stats_skater_team_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_skater_org_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_skater_human_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_skater_game_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_skater_game_date'))
        batch_op.drop_index('idx_game_stats_skater_human_team_date', postgresql_using='btree')
        batch_op.drop_index('idx_game_stats_skater_human_date', postgresql_using='btree')

    op.drop_table('game_stats_skater')
    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_stats_goalie_team_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_goalie_org_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_goalie_human_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_goalie_game_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_goalie_game_date'))
        batch_op.drop_index('idx_game_stats_goalie_human_team_date', postgresql_using='btree')
        batch_op.drop_index('idx_game_stats_goalie_human_date', postgresql_using='btree')

    op.drop_table('game_stats_goalie')
    # ### end Alembic commands ###
