"""Skill in Human

Revision ID: 1557ad932d05
Revises: f3facb0580dd
Create Date: 2025-01-31 14:23:39.505034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1557ad932d05'
down_revision = 'f3facb0580dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skater_skill_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.drop_column('skater_skill_value')

    # ### end Alembic commands ###
