"""Add suffix field to Human and HumanAlias models

Revision ID: 1bac2ab821e5
Revises: cdf084f40be3
Create Date: 2025-09-25 13:29:02.451136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bac2ab821e5'
down_revision = 'cdf084f40be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('_human_alias_uc', type_='unique')
        batch_op.create_unique_constraint('_human_alias_uc', ['human_id', 'first_name', 'middle_name', 'last_name', 'suffix'])

    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suffix', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('_human_name_uc', type_='unique')
        batch_op.create_unique_constraint('_human_name_uc', ['first_name', 'middle_name', 'last_name', 'suffix'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.drop_constraint('_human_name_uc', type_='unique')
        batch_op.create_unique_constraint('_human_name_uc', ['first_name', 'middle_name', 'last_name'])
        batch_op.drop_column('suffix')

    with op.batch_alter_table('human_aliases', schema=None) as batch_op:
        batch_op.drop_constraint('_human_alias_uc', type_='unique')
        batch_op.create_unique_constraint('_human_alias_uc', ['human_id', 'first_name', 'middle_name', 'last_name'])
        batch_op.drop_column('suffix')

    # ### end Alembic commands ###
