"""Add games_participated and games_with_stats fields to all stats models

Revision ID: 2186b7edf024
Revises: 86648b92c5f3
Create Date: 2025-10-07 17:19:18.414839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2186b7edf024'
down_revision = '86648b92c5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('level_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_participated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_participated_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('games_with_stats_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('level_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_weekly_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_daily_referee', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_column('games_with_stats_rank')
        batch_op.drop_column('games_with_stats')
        batch_op.drop_column('games_participated_rank')
        batch_op.drop_column('games_participated')

    # ### end Alembic commands ###
