"""add h2h

Revision ID: 22c84969be75
Revises: 95d61fa0715e
Create Date: 2025-05-29 18:59:05.435792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c84969be75'
down_revision = '95d61fa0715e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h2h_stats_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_processed_game_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('h2h_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human1_id', sa.Integer(), nullable=False),
    sa.Column('human2_id', sa.Integer(), nullable=False),
    sa.Column('games_together', sa.Integer(), nullable=True),
    sa.Column('games_against', sa.Integer(), nullable=True),
    sa.Column('games_tied_together', sa.Integer(), nullable=True),
    sa.Column('games_tied_against', sa.Integer(), nullable=True),
    sa.Column('wins_together', sa.Integer(), nullable=True),
    sa.Column('losses_together', sa.Integer(), nullable=True),
    sa.Column('h1_wins_vs_h2', sa.Integer(), nullable=True),
    sa.Column('h2_wins_vs_h1', sa.Integer(), nullable=True),
    sa.Column('games_h1_goalie', sa.Integer(), nullable=True),
    sa.Column('games_h2_goalie', sa.Integer(), nullable=True),
    sa.Column('games_h1_ref', sa.Integer(), nullable=True),
    sa.Column('games_h2_ref', sa.Integer(), nullable=True),
    sa.Column('games_both_referees', sa.Integer(), nullable=True),
    sa.Column('goals_h1_when_together', sa.Integer(), nullable=True),
    sa.Column('goals_h2_when_together', sa.Integer(), nullable=True),
    sa.Column('assists_h1_when_together', sa.Integer(), nullable=True),
    sa.Column('assists_h2_when_together', sa.Integer(), nullable=True),
    sa.Column('penalties_h1_when_together', sa.Integer(), nullable=True),
    sa.Column('penalties_h2_when_together', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_h1_when_together', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_h2_when_together', sa.Integer(), nullable=True),
    sa.Column('h1_goalie_h2_scorer_goals', sa.Integer(), nullable=True),
    sa.Column('h2_goalie_h1_scorer_goals', sa.Integer(), nullable=True),
    sa.Column('shots_faced_h1_goalie_vs_h2', sa.Integer(), nullable=True),
    sa.Column('shots_faced_h2_goalie_vs_h1', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_h1_goalie_vs_h2', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_h2_goalie_vs_h1', sa.Integer(), nullable=True),
    sa.Column('save_percentage_h1_goalie_vs_h2', sa.Float(), nullable=True),
    sa.Column('save_percentage_h2_goalie_vs_h1', sa.Float(), nullable=True),
    sa.Column('h1_ref_h2_player_games', sa.Integer(), nullable=True),
    sa.Column('h2_ref_h1_player_games', sa.Integer(), nullable=True),
    sa.Column('h1_ref_penalties_on_h2', sa.Integer(), nullable=True),
    sa.Column('h2_ref_penalties_on_h1', sa.Integer(), nullable=True),
    sa.Column('h1_ref_gm_penalties_on_h2', sa.Integer(), nullable=True),
    sa.Column('h2_ref_gm_penalties_on_h1', sa.Integer(), nullable=True),
    sa.Column('penalties_given_both_refs', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_given_both_refs', sa.Integer(), nullable=True),
    sa.Column('h1_shootout_attempts_vs_h2_goalie', sa.Integer(), nullable=True),
    sa.Column('h1_shootout_goals_vs_h2_goalie', sa.Integer(), nullable=True),
    sa.Column('h2_shootout_attempts_vs_h1_goalie', sa.Integer(), nullable=True),
    sa.Column('h2_shootout_goals_vs_h1_goalie', sa.Integer(), nullable=True),
    sa.Column('first_game_id', sa.Integer(), nullable=False),
    sa.Column('last_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['human1_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['human2_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human1_id', 'human2_id', name='_h2h_human_pair_uc')
    )
    with op.batch_alter_table('h2h_stats', schema=None) as batch_op:
        batch_op.create_index('ix_h2h_human_pair', ['human1_id', 'human2_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('h2h_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_h2h_human_pair')

    op.drop_table('h2h_stats')
    op.drop_table('h2h_stats_meta')
    # ### end Alembic commands ###
