"""Add current_point_streak

Revision ID: 2950fe04aec2
Revises: bbb48c317afc
Create Date: 2025-09-05 23:36:04.870173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2950fe04aec2'
down_revision = 'bbb48c317afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_daily_current_point_streak3', ['division_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_division_daily_current_point_streak_avg_points3', ['division_id', 'current_point_streak_avg_points'], unique=False)

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_current_point_streak3', ['division_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_division_current_point_streak_avg_points3', ['division_id', 'current_point_streak_avg_points'], unique=False)

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_weekly_current_point_streak3', ['division_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_division_weekly_current_point_streak_avg_points3', ['division_id', 'current_point_streak_avg_points'], unique=False)

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_level_current_point_streak3', ['level_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_level_current_point_streak_avg_points3', ['level_id', 'current_point_streak_avg_points'], unique=False)

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_daily_current_point_streak3', ['org_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_org_daily_current_point_streak_avg_points3', ['org_id', 'current_point_streak_avg_points'], unique=False)

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_current_point_streak3', ['org_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_org_current_point_streak_avg_points3', ['org_id', 'current_point_streak_avg_points'], unique=False)

    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_point_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_weekly_current_point_streak3', ['org_id', 'current_point_streak'], unique=False)
        batch_op.create_index('idx_org_weekly_current_point_streak_avg_points3', ['org_id', 'current_point_streak_avg_points'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_current_point_streak_avg_points3')
        batch_op.drop_index('idx_org_weekly_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_current_point_streak_avg_points3')
        batch_op.drop_index('idx_org_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_current_point_streak_avg_points3')
        batch_op.drop_index('idx_org_daily_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_level_current_point_streak_avg_points3')
        batch_op.drop_index('idx_level_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_current_point_streak_avg_points3')
        batch_op.drop_index('idx_division_weekly_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_current_point_streak_avg_points3')
        batch_op.drop_index('idx_division_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_current_point_streak_avg_points3')
        batch_op.drop_index('idx_division_daily_current_point_streak3')
        batch_op.drop_column('current_point_streak_avg_points_rank')
        batch_op.drop_column('current_point_streak_avg_points')
        batch_op.drop_column('current_point_streak_rank')
        batch_op.drop_column('current_point_streak')

    # ### end Alembic commands ###
