"""Add nullable is_seed field to Skill model

Revision ID: 295e021213c6
Revises: 5c1cfe435d02
Create Date: 2025-01-25 16:29:29.940190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295e021213c6'
down_revision = '5c1cfe435d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_seed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('is_seed')

    # ### end Alembic commands ###
