"""Add goalie_id field to goals table for tracking goalie who allowed goal

Revision ID: 2fe072baf4ba
Revises: 3328cfeb5c5a
Create Date: 2025-09-10 12:54:28.989651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe072baf4ba'
down_revision = '3328cfeb5c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goalie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'humans', ['goalie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goalie_id')

    # ### end Alembic commands ###
