"""Add gm_penalties fields to BaseStatsSkater

Revision ID: 306d196cfdf6
Revises: 636dfbb54427
Create Date: 2025-02-14 17:15:54.480772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306d196cfdf6'
down_revision = '636dfbb54427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_column('gm_penalties_rank')
        batch_op.drop_column('gm_penalties')

    # ### end Alembic commands ###
