"""org id not nullable in team

Revision ID: 3328cfeb5c5a
Revises: 02e745dc14a9
Create Date: 2025-09-09 16:11:55.902031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3328cfeb5c5a'
down_revision = '02e745dc14a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_unique_constraint('_org_league_season_level_uc', ['org_id', 'league_number', 'season_number', 'level'])

    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.create_unique_constraint('_human_name_uc', ['first_name', 'middle_name', 'last_name'])

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_unique_constraint('_org_level_name_uc', ['org_id', 'level_name'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('org_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint('_org_level_name_uc', type_='unique')

    with op.batch_alter_table('humans', schema=None) as batch_op:
        batch_op.drop_constraint('_human_name_uc', type_='unique')

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_constraint('_org_league_season_level_uc', type_='unique')

    # ### end Alembic commands ###
