"""Rename human_game_cache to human_games

Revision ID: 3887ae51ff2e
Revises: 007ae3e9eb49
Create Date: 2026-02-05 00:25:00.306341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3887ae51ff2e'
down_revision = '007ae3e9eb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_games',
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('game_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('games_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_processed_games_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('human_id')
    )
    with op.batch_alter_table('human_games', schema=None) as batch_op:
        batch_op.create_index('idx_human_games_games_count', ['games_count'], unique=False)
        batch_op.create_index('idx_human_games_last_updated', ['last_updated_at'], unique=False)
        batch_op.create_index('idx_human_games_needs_processing', ['games_count', 'last_processed_games_count'], unique=False)

    with op.batch_alter_table('human_game_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_human_game_cache_games_count')
        batch_op.drop_index('idx_human_game_cache_last_updated')
        batch_op.drop_index('idx_human_game_cache_needs_processing')

    op.drop_table('human_game_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_game_cache',
    sa.Column('human_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('games_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_processed_games_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], name='human_game_cache_human_id_fkey'),
    sa.PrimaryKeyConstraint('human_id', name='human_game_cache_pkey')
    )
    with op.batch_alter_table('human_game_cache', schema=None) as batch_op:
        batch_op.create_index('idx_human_game_cache_needs_processing', ['games_count', 'last_processed_games_count'], unique=False)
        batch_op.create_index('idx_human_game_cache_last_updated', ['last_updated_at'], unique=False)
        batch_op.create_index('idx_human_game_cache_games_count', ['games_count'], unique=False)

    with op.batch_alter_table('human_games', schema=None) as batch_op:
        batch_op.drop_index('idx_human_games_needs_processing')
        batch_op.drop_index('idx_human_games_last_updated')
        batch_op.drop_index('idx_human_games_games_count')

    op.drop_table('human_games')
    # ### end Alembic commands ###
