"""Add gm_penalties_per_game and rank for it

Revision ID: 3b05e05a0ad6
Revises: 306d196cfdf6
Create Date: 2025-02-14 19:03:11.957741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b05e05a0ad6'
down_revision = '306d196cfdf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_daily_gm_penalties_per_game3', ['division_id', 'gm_penalties_per_game'], unique=False)

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_gm_penalties_per_game3', ['division_id', 'gm_penalties_per_game'], unique=False)

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_weekly_gm_penalties_per_game3', ['division_id', 'gm_penalties_per_game'], unique=False)

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_level_gm_penalties_per_game3', ['level_id', 'gm_penalties_per_game'], unique=False)

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_daily_gm_penalties_per_game3', ['org_id', 'gm_penalties_per_game'], unique=False)

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_gm_penalties_per_game3', ['org_id', 'gm_penalties_per_game'], unique=False)

    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gm_penalties_per_game', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_weekly_gm_penalties_per_game3', ['org_id', 'gm_penalties_per_game'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    with op.batch_alter_table('org_stats_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    with op.batch_alter_table('org_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    with op.batch_alter_table('level_stats_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_level_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    with op.batch_alter_table('division_stats_weekly_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    with op.batch_alter_table('division_stats_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    with op.batch_alter_table('division_stats_daily_skater', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_gm_penalties_per_game3')
        batch_op.drop_column('gm_penalties_per_game_rank')
        batch_op.drop_column('gm_penalties_per_game')

    # ### end Alembic commands ###
