"""Manually renamed tables, fake migration

Revision ID: 3bc694f30253
Revises: efebc8e5d2a3
Create Date: 2025-01-29 16:58:07.050252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc694f30253'
down_revision = 'efebc8e5d2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('divisions_skill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])
        batch_op.drop_column('skill_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('divisions_skill_id_fkey', 'levels', ['skill_id'], ['id'])
        batch_op.drop_column('level_id')

    # ### end Alembic commands ###
