"""Refactor Location: add location_in_game_source, make all fields except id optional

Revision ID: 43823ff75fe6
Revises: f7a04b6be8b9
Create Date: 2025-11-25 18:29:38.932902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43823ff75fe6'
down_revision = 'f7a04b6be8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_in_game_source', sa.String(length=200), nullable=False))
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('rink_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_constraint('_location_rink_name_uc', type_='unique')
        batch_op.create_unique_constraint(None, ['location_in_game_source'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('_location_rink_name_uc', ['location_name', 'rink_name'])
        batch_op.alter_column('rink_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('location_in_game_source')

    # ### end Alembic commands ###
