"""Add short_name field to Level model

Revision ID: 4545bbed2826
Revises: f0ebc31a430d
Create Date: 2025-12-02 00:53:39.943138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4545bbed2826'
down_revision = 'f0ebc31a430d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_column('short_name')

    # ### end Alembic commands ###
