"""Add live_time field to Game model

Revision ID: 4c7b6623e76e
Revises: 43823ff75fe6
Create Date: 2025-11-25 23:43:54.710019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7b6623e76e'
down_revision = '43823ff75fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_time', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('live_time')

    # ### end Alembic commands ###
