"""Add team-based statistics tables with human_id aggregation

Revision ID: 4db5c221dd97
Revises: ae2a684b1657
Create Date: 2025-11-04 00:45:47.103354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db5c221dd97'
down_revision = 'ae2a684b1657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_constraint('_team_division_uc_goalie_team1', type_='unique')
        batch_op.create_unique_constraint('_division_team_human_uc_goalie_team1', ['division_id', 'team_id', 'human_id'])
        batch_op.create_index('idx_division_team_goalie_human_id', ['human_id'], unique=False)

    with op.batch_alter_table('division_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_constraint('_team_division_uc_skater_team1', type_='unique')
        batch_op.create_unique_constraint('_division_team_human_uc_skater_team1', ['division_id', 'team_id', 'human_id'])
        batch_op.create_index('idx_division_team_human_id', ['human_id'], unique=False)

    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_constraint('_team_org_uc_goalie_team1', type_='unique')
        batch_op.create_unique_constraint('_org_team_human_uc_goalie_team1', ['org_id', 'team_id', 'human_id'])
        batch_op.create_index('idx_org_team_goalie_human_id', ['human_id'], unique=False)

    with op.batch_alter_table('org_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_constraint('_team_org_uc_skater_team1', type_='unique')
        batch_op.create_unique_constraint('_org_team_human_uc_skater_team1', ['org_id', 'team_id', 'human_id'])
        batch_op.create_index('idx_org_team_human_id', ['human_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_index('idx_org_team_human_id')
        batch_op.drop_constraint('_org_team_human_uc_skater_team1', type_='unique')
        batch_op.create_unique_constraint('_team_org_uc_skater_team1', ['team_id', 'org_id'])

    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_index('idx_org_team_goalie_human_id')
        batch_op.drop_constraint('_org_team_human_uc_goalie_team1', type_='unique')
        batch_op.create_unique_constraint('_team_org_uc_goalie_team1', ['team_id', 'org_id'])

    with op.batch_alter_table('division_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_index('idx_division_team_human_id')
        batch_op.drop_constraint('_division_team_human_uc_skater_team1', type_='unique')
        batch_op.create_unique_constraint('_team_division_uc_skater_team1', ['team_id', 'division_id'])

    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_index('idx_division_team_goalie_human_id')
        batch_op.drop_constraint('_division_team_human_uc_goalie_team1', type_='unique')
        batch_op.create_unique_constraint('_team_division_uc_goalie_team1', ['team_id', 'division_id'])

    # ### end Alembic commands ###
