"""Add human_embeddings and team_embeddings tables for vector search

Revision ID: 4ee5af9b587d
Revises: 5874a5055898
Create Date: 2025-11-02 13:11:23.596600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee5af9b587d'
down_revision = '5874a5055898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_embeddings',
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('human_id')
    )
    # Add vector column with proper pgvector type
    op.execute('ALTER TABLE human_embeddings ADD COLUMN embedding vector(1024) NOT NULL')
    # Create index for vector similarity search (using cosine distance)
    op.execute('CREATE INDEX idx_human_embeddings_vector ON human_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)')

    op.create_table('team_embeddings',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    # Add vector column with proper pgvector type
    op.execute('ALTER TABLE team_embeddings ADD COLUMN embedding vector(1024) NOT NULL')
    # Create index for vector similarity search (using cosine distance)
    op.execute('CREATE INDEX idx_team_embeddings_vector ON team_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_embeddings')
    op.drop_table('human_embeddings')
    # ### end Alembic commands ###
