"""UC for duplicate goals

Revision ID: 5874a5055898
Revises: 2186b7edf024
Create Date: 2025-10-08 00:13:05.566741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5874a5055898'
down_revision = '2186b7edf024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_goals_no_duplicates', ['game_id', 'period', 'time', 'goal_scorer_id', 'scoring_team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_constraint('uq_goals_no_duplicates', type_='unique')

    # ### end Alembic commands ###
