"""Add response_time_ms to RequestLog table

Revision ID: 5c7c11591cd5
Revises: 2950fe04aec2
Create Date: 2025-09-06 00:20:29.085654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7c11591cd5'
down_revision = '2950fe04aec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_time_ms', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('response_time_ms')

    # ### end Alembic commands ###
