"""Goalie stats extension to level aggr window

Revision ID: 5cc9202e5fb0
Revises: 1557ad932d05
Create Date: 2025-02-03 12:47:35.843853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc9202e5fb0'
down_revision = '1557ad932d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_stats_goalie',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_rank', sa.Integer(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_rank', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_rank', sa.Integer(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_rank', sa.Integer(), nullable=True),
    sa.Column('total_in_rank', sa.Integer(), nullable=True),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('last_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('human_id', 'level_id', name='_human_level_uc_goalie1')
    )
    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.create_index('idx_level_games_played_goalie1', ['level_id', 'games_played'], unique=False)
        batch_op.create_index('idx_level_goals_allowed1', ['level_id', 'goals_allowed'], unique=False)
        batch_op.create_index('idx_level_goals_allowed_per_game1', ['level_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_level_save_percentage1', ['level_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_level_shots_faced1', ['level_id', 'shots_faced'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_level_shots_faced1')
        batch_op.drop_index('idx_level_save_percentage1')
        batch_op.drop_index('idx_level_goals_allowed_per_game1')
        batch_op.drop_index('idx_level_goals_allowed1')
        batch_op.drop_index('idx_level_games_played_goalie1')

    op.drop_table('level_stats_goalie')
    # ### end Alembic commands ###
