"""Add cgi params to request logging

Revision ID: 636dfbb54427
Revises: a491eafdc42f
Create Date: 2025-02-12 15:54:51.889770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636dfbb54427'
down_revision = 'a491eafdc42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgi_params', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('cgi_params')

    # ### end Alembic commands ###
