"""Add league_id field to Season model

Revision ID: 64807af5172b
Revises: 408ac8540fc1
Create Date: 2025-01-27 16:04:48.867289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64807af5172b'
down_revision = '408ac8540fc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('league_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'leagues', ['league_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('league_id')

    # ### end Alembic commands ###
