"""add goalie win loss shutout tracking

Revision ID: 7bb61ab19ff0
Revises: a1b2c3d4e5f6
Create Date: 2026-05-13 10:08:20.275858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb61ab19ff0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_daily_shutouts_goalie1', ['division_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_division_daily_win_percentage_goalie1', ['division_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_division_daily_wins_goalie1', ['division_id', 'wins'], unique=False)

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_shutouts_goalie1', ['division_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_division_win_percentage_goalie1', ['division_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_division_wins_goalie1', ['division_id', 'wins'], unique=False)

    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_division_weekly_shutouts_goalie1', ['division_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_division_weekly_win_percentage_goalie1', ['division_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_division_weekly_wins_goalie1', ['division_id', 'wins'], unique=False)

    # division_team_standings indexes removed - already exist

    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('shutout', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # human_aliases changes removed - unrelated autogenerate noise

    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_level_shutouts_goalie1', ['level_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_level_win_percentage_goalie1', ['level_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_level_wins_goalie1', ['level_id', 'wins'], unique=False)

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_daily_shutouts_goalie1', ['org_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_org_daily_win_percentage_goalie1', ['org_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_org_daily_wins_goalie1', ['org_id', 'wins'], unique=False)

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_shutouts_goalie1', ['org_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_org_win_percentage_goalie1', ['org_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_org_wins_goalie1', ['org_id', 'wins'], unique=False)

    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ties', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ot_losses_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shutouts_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('win_percentage_rank', sa.Integer(), nullable=True))
        batch_op.create_index('idx_org_weekly_shutouts_goalie1', ['org_id', 'shutouts'], unique=False)
        batch_op.create_index('idx_org_weekly_win_percentage_goalie1', ['org_id', 'win_percentage'], unique=False)
        batch_op.create_index('idx_org_weekly_wins_goalie1', ['org_id', 'wins'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_org_weekly_wins_goalie1')
        batch_op.drop_index('idx_org_weekly_win_percentage_goalie1')
        batch_op.drop_index('idx_org_weekly_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('org_stats_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_org_wins_goalie1')
        batch_op.drop_index('idx_org_win_percentage_goalie1')
        batch_op.drop_index('idx_org_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('org_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_org_daily_wins_goalie1')
        batch_op.drop_index('idx_org_daily_win_percentage_goalie1')
        batch_op.drop_index('idx_org_daily_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('level_stats_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_level_wins_goalie1')
        batch_op.drop_index('idx_level_win_percentage_goalie1')
        batch_op.drop_index('idx_level_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    # human_aliases changes removed - unrelated autogenerate noise

    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.drop_column('shutout')
        batch_op.drop_column('result')

    # division_team_standings index drops removed - unrelated

    with op.batch_alter_table('division_stats_weekly_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_wins_goalie1')
        batch_op.drop_index('idx_division_weekly_win_percentage_goalie1')
        batch_op.drop_index('idx_division_weekly_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('division_stats_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_division_wins_goalie1')
        batch_op.drop_index('idx_division_win_percentage_goalie1')
        batch_op.drop_index('idx_division_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    with op.batch_alter_table('division_stats_daily_goalie', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_wins_goalie1')
        batch_op.drop_index('idx_division_daily_win_percentage_goalie1')
        batch_op.drop_index('idx_division_daily_shutouts_goalie1')
        batch_op.drop_column('win_percentage_rank')
        batch_op.drop_column('win_percentage')
        batch_op.drop_column('shutouts_rank')
        batch_op.drop_column('shutouts')
        batch_op.drop_column('ot_losses_rank')
        batch_op.drop_column('ot_losses')
        batch_op.drop_column('ties')
        batch_op.drop_column('losses_rank')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins_rank')
        batch_op.drop_column('wins')

    # ### end Alembic commands ###
