"""Add base_season_name field to Season model

Revision ID: 7d7bc4528315
Revises: 1010723436cb
Create Date: 2025-11-25 09:11:09.117802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7bc4528315'
down_revision = '1010723436cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_season_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('base_season_name')

    # ### end Alembic commands ###
