"""zeroes non null h2h - take two

Revision ID: 7eb05b15d6df
Revises: 97620bd96fa5
Create Date: 2025-05-29 19:11:23.638933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb05b15d6df'
down_revision = '97620bd96fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('h2h_stats', schema=None) as batch_op:
        batch_op.alter_column('games_tied_against',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wins_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('losses_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h1_wins_vs_h2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_wins_vs_h1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_h1_goalie',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_h2_goalie',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_h1_ref',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_h2_ref',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_both_referees',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('goals_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('goals_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('assists_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('assists_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('penalties_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('penalties_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gm_penalties_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gm_penalties_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h1_goalie_h2_scorer_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_goalie_h1_scorer_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shots_faced_h1_goalie_vs_h2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('shots_faced_h2_goalie_vs_h1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('goals_allowed_h1_goalie_vs_h2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('goals_allowed_h2_goalie_vs_h1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('save_percentage_h1_goalie_vs_h2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('save_percentage_h2_goalie_vs_h1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('h1_ref_h2_player_games',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_ref_h1_player_games',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h1_ref_penalties_on_h2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_ref_penalties_on_h1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h1_ref_gm_penalties_on_h2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_ref_gm_penalties_on_h1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('penalties_given_both_refs',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gm_penalties_given_both_refs',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h1_shootout_attempts_vs_h2_goalie',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h1_shootout_goals_vs_h2_goalie',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_shootout_attempts_vs_h1_goalie',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('h2_shootout_goals_vs_h1_goalie',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('h2h_stats', schema=None) as batch_op:
        batch_op.alter_column('h2_shootout_goals_vs_h1_goalie',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h2_shootout_attempts_vs_h1_goalie',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_shootout_goals_vs_h2_goalie',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_shootout_attempts_vs_h2_goalie',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gm_penalties_given_both_refs',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('penalties_given_both_refs',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h2_ref_gm_penalties_on_h1',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_ref_gm_penalties_on_h2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h2_ref_penalties_on_h1',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_ref_penalties_on_h2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h2_ref_h1_player_games',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_ref_h2_player_games',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('save_percentage_h2_goalie_vs_h1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('save_percentage_h1_goalie_vs_h2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('goals_allowed_h2_goalie_vs_h1',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('goals_allowed_h1_goalie_vs_h2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shots_faced_h2_goalie_vs_h1',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shots_faced_h1_goalie_vs_h2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h2_goalie_h1_scorer_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_goalie_h2_scorer_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gm_penalties_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gm_penalties_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('penalties_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('penalties_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assists_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('assists_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('goals_h2_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('goals_h1_when_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_both_referees',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_h2_ref',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_h1_ref',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_h2_goalie',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_h1_goalie',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h2_wins_vs_h1',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('h1_wins_vs_h2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('losses_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wins_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_tied_against',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
