"""Separate totals in rank per role in human stats

Revision ID: 7ed611b8dba5
Revises: 3f29488f7592
Create Date: 2025-02-04 13:04:43.753623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed611b8dba5'
down_revision = '3f29488f7592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('level_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skaters_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goalies_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referees_in_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scorekeepers_in_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('org_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    with op.batch_alter_table('org_stats_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    with op.batch_alter_table('org_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    with op.batch_alter_table('level_stats_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    with op.batch_alter_table('division_stats_weekly_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    with op.batch_alter_table('division_stats_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    with op.batch_alter_table('division_stats_daily_human', schema=None) as batch_op:
        batch_op.drop_column('scorekeepers_in_rank')
        batch_op.drop_column('referees_in_rank')
        batch_op.drop_column('goalies_in_rank')
        batch_op.drop_column('skaters_in_rank')

    # ### end Alembic commands ###
