"""Update HumanPrivacyOptOut to use name fields instead of human_id

Revision ID: 86648b92c5f3
Revises: 982973d94657
Create Date: 2025-10-01 13:18:30.984211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86648b92c5f3'
down_revision = '982973d94657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_privacy_opt_outs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=100), nullable=False),
    sa.Column('opt_out_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'middle_name', 'last_name', 'suffix', name='_privacy_optout_name_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human_privacy_opt_outs')
    # ### end Alembic commands ###
