"""Add SkillPropagationCorrelation

Revision ID: 929f87c61fa3
Revises: 3ae7f7c42b44
Create Date: 2025-01-28 22:16:10.258932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929f87c61fa3'
down_revision = '3ae7f7c42b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_propagation_correlation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_value_from', sa.Float(), nullable=False),
    sa.Column('skill_value_to', sa.Float(), nullable=False),
    sa.Column('ppg_ratio', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_value_from', 'skill_value_to', 'ppg_ratio', name='_skill_value_ppg_ratio_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_propagation_correlation')
    # ### end Alembic commands ###
