"""Add website field to Organization

Revision ID: 9582205c5ac8
Revises: 7ed611b8dba5
Create Date: 2025-02-05 13:45:57.122987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9582205c5ac8'
down_revision = '7ed611b8dba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
