"""zeroes non null h2h

Revision ID: 97620bd96fa5
Revises: 22c84969be75
Create Date: 2025-05-29 19:07:05.178543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97620bd96fa5'
down_revision = '22c84969be75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('h2h_stats', schema=None) as batch_op:
        batch_op.alter_column('games_together',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_against',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('games_tied_together',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('h2h_stats', schema=None) as batch_op:
        batch_op.alter_column('games_tied_together',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_against',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('games_together',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
