"""Remove division scorekeeper stats tables

Revision ID: 982973d94657
Revises: 5cfc8ca17c9c
Create Date: 2025-09-29 15:14:32.792125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982973d94657'
down_revision = '5cfc8ca17c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_division_weekly_avg_max_saves_per_20sec1')
        batch_op.drop_index('idx_division_weekly_avg_max_saves_per_5sec1')
        batch_op.drop_index('idx_division_weekly_avg_saves_per_game1')
        batch_op.drop_index('idx_division_weekly_games_recorded1')
        batch_op.drop_index('idx_division_weekly_peak_max_saves_per_20sec1')
        batch_op.drop_index('idx_division_weekly_peak_max_saves_per_5sec1')
        batch_op.drop_index('idx_division_weekly_quality_score1')
        batch_op.drop_index('idx_division_weekly_sog_given1')
        batch_op.drop_index('idx_division_weekly_sog_per_game1')
        batch_op.drop_index('idx_division_weekly_total_saves_recorded1')

    op.drop_table('division_stats_weekly_scorekeeper')
    with op.batch_alter_table('division_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_division_daily_avg_max_saves_per_20sec1')
        batch_op.drop_index('idx_division_daily_avg_max_saves_per_5sec1')
        batch_op.drop_index('idx_division_daily_avg_saves_per_game1')
        batch_op.drop_index('idx_division_daily_games_recorded1')
        batch_op.drop_index('idx_division_daily_peak_max_saves_per_20sec1')
        batch_op.drop_index('idx_division_daily_peak_max_saves_per_5sec1')
        batch_op.drop_index('idx_division_daily_quality_score1')
        batch_op.drop_index('idx_division_daily_sog_given1')
        batch_op.drop_index('idx_division_daily_sog_per_game1')
        batch_op.drop_index('idx_division_daily_total_saves_recorded1')

    op.drop_table('division_stats_daily_scorekeeper')
    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.drop_index('idx_division_avg_max_saves_per_20sec1')
        batch_op.drop_index('idx_division_avg_max_saves_per_5sec1')
        batch_op.drop_index('idx_division_avg_saves_per_game1')
        batch_op.drop_index('idx_division_games_recorded1')
        batch_op.drop_index('idx_division_peak_max_saves_per_20sec1')
        batch_op.drop_index('idx_division_peak_max_saves_per_5sec1')
        batch_op.drop_index('idx_division_quality_score1')
        batch_op.drop_index('idx_division_sog_given1')
        batch_op.drop_index('idx_division_sog_per_game1')
        batch_op.drop_index('idx_division_total_saves_recorded1')

    op.drop_table('division_stats_scorekeeper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division_stats_scorekeeper',
    sa.Column('division_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('human_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_recorded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_given', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('games_recorded_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_given_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_per_game_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_in_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_saves_recorded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_saves_recorded_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_game_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_5sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_5sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_20sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_20sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_5sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_5sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_20sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_20sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name='division_stats_scorekeeper_division_id_fkey'),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], name='division_stats_scorekeeper_first_game_id_fkey'),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], name='division_stats_scorekeeper_human_id_fkey'),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], name='division_stats_scorekeeper_last_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='division_stats_scorekeeper_pkey'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_uc_scorekeeper1')
    )
    with op.batch_alter_table('division_stats_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_division_total_saves_recorded1', ['division_id', 'total_saves_recorded'], unique=False)
        batch_op.create_index('idx_division_sog_per_game1', ['division_id', 'sog_per_game'], unique=False)
        batch_op.create_index('idx_division_sog_given1', ['division_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_division_quality_score1', ['division_id', 'quality_score'], unique=False)
        batch_op.create_index('idx_division_peak_max_saves_per_5sec1', ['division_id', 'peak_max_saves_per_5sec'], unique=False)
        batch_op.create_index('idx_division_peak_max_saves_per_20sec1', ['division_id', 'peak_max_saves_per_20sec'], unique=False)
        batch_op.create_index('idx_division_games_recorded1', ['division_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_division_avg_saves_per_game1', ['division_id', 'avg_saves_per_game'], unique=False)
        batch_op.create_index('idx_division_avg_max_saves_per_5sec1', ['division_id', 'avg_max_saves_per_5sec'], unique=False)
        batch_op.create_index('idx_division_avg_max_saves_per_20sec1', ['division_id', 'avg_max_saves_per_20sec'], unique=False)

    op.create_table('division_stats_daily_scorekeeper',
    sa.Column('division_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('human_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_recorded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_given', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('games_recorded_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_given_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_per_game_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_in_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_saves_recorded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_saves_recorded_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_game_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_5sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_5sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_20sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_20sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_5sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_5sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_20sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_20sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name='division_stats_daily_scorekeeper_division_id_fkey'),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], name='division_stats_daily_scorekeeper_first_game_id_fkey'),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], name='division_stats_daily_scorekeeper_human_id_fkey'),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], name='division_stats_daily_scorekeeper_last_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='division_stats_daily_scorekeeper_pkey'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_daily_uc_scorekeeper1')
    )
    with op.batch_alter_table('division_stats_daily_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_division_daily_total_saves_recorded1', ['division_id', 'total_saves_recorded'], unique=False)
        batch_op.create_index('idx_division_daily_sog_per_game1', ['division_id', 'sog_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_sog_given1', ['division_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_division_daily_quality_score1', ['division_id', 'quality_score'], unique=False)
        batch_op.create_index('idx_division_daily_peak_max_saves_per_5sec1', ['division_id', 'peak_max_saves_per_5sec'], unique=False)
        batch_op.create_index('idx_division_daily_peak_max_saves_per_20sec1', ['division_id', 'peak_max_saves_per_20sec'], unique=False)
        batch_op.create_index('idx_division_daily_games_recorded1', ['division_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_division_daily_avg_saves_per_game1', ['division_id', 'avg_saves_per_game'], unique=False)
        batch_op.create_index('idx_division_daily_avg_max_saves_per_5sec1', ['division_id', 'avg_max_saves_per_5sec'], unique=False)
        batch_op.create_index('idx_division_daily_avg_max_saves_per_20sec1', ['division_id', 'avg_max_saves_per_20sec'], unique=False)

    op.create_table('division_stats_weekly_scorekeeper',
    sa.Column('division_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('human_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games_recorded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_given', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('first_game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('games_recorded_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_given_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sog_per_game_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_in_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_saves_recorded', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_saves_recorded_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_saves_per_game_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_5sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_5sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_20sec', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_max_saves_per_20sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_5sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_5sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_20sec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_max_saves_per_20sec_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name='division_stats_weekly_scorekeeper_division_id_fkey'),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], name='division_stats_weekly_scorekeeper_first_game_id_fkey'),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], name='division_stats_weekly_scorekeeper_human_id_fkey'),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], name='division_stats_weekly_scorekeeper_last_game_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='division_stats_weekly_scorekeeper_pkey'),
    sa.UniqueConstraint('human_id', 'division_id', name='_human_division_weekly_uc_scorekeeper1')
    )
    with op.batch_alter_table('division_stats_weekly_scorekeeper', schema=None) as batch_op:
        batch_op.create_index('idx_division_weekly_total_saves_recorded1', ['division_id', 'total_saves_recorded'], unique=False)
        batch_op.create_index('idx_division_weekly_sog_per_game1', ['division_id', 'sog_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_sog_given1', ['division_id', 'sog_given'], unique=False)
        batch_op.create_index('idx_division_weekly_quality_score1', ['division_id', 'quality_score'], unique=False)
        batch_op.create_index('idx_division_weekly_peak_max_saves_per_5sec1', ['division_id', 'peak_max_saves_per_5sec'], unique=False)
        batch_op.create_index('idx_division_weekly_peak_max_saves_per_20sec1', ['division_id', 'peak_max_saves_per_20sec'], unique=False)
        batch_op.create_index('idx_division_weekly_games_recorded1', ['division_id', 'games_recorded'], unique=False)
        batch_op.create_index('idx_division_weekly_avg_saves_per_game1', ['division_id', 'avg_saves_per_game'], unique=False)
        batch_op.create_index('idx_division_weekly_avg_max_saves_per_5sec1', ['division_id', 'avg_max_saves_per_5sec'], unique=False)
        batch_op.create_index('idx_division_weekly_avg_max_saves_per_20sec1', ['division_id', 'avg_max_saves_per_20sec'], unique=False)

    # ### end Alembic commands ###
