"""Add team-based statistics tables (org and division)

Revision ID: ae2a684b1657
Revises: 4ee5af9b587d
Create Date: 2025-11-04 00:35:46.306077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2a684b1657'
down_revision = '4ee5af9b587d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division_stats_goalie_team',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_rank', sa.Integer(), nullable=True),
    sa.Column('games_participated', sa.Integer(), nullable=True),
    sa.Column('games_participated_rank', sa.Integer(), nullable=True),
    sa.Column('games_with_stats', sa.Integer(), nullable=True),
    sa.Column('games_with_stats_rank', sa.Integer(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_rank', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_rank', sa.Integer(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_rank', sa.Integer(), nullable=True),
    sa.Column('total_in_rank', sa.Integer(), nullable=True),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('last_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'division_id', name='_team_division_uc_goalie_team1')
    )
    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.create_index('idx_division_team_goalie_gaa', ['division_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_division_team_goalie_save_pct', ['division_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_division_team_goalie_team_id', ['team_id'], unique=False)

    op.create_table('division_stats_skater_team',
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_rank', sa.Integer(), nullable=True),
    sa.Column('games_participated', sa.Integer(), nullable=True),
    sa.Column('games_participated_rank', sa.Integer(), nullable=True),
    sa.Column('games_with_stats', sa.Integer(), nullable=True),
    sa.Column('games_with_stats_rank', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_rank', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('assists_rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_rank', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalties_rank', sa.Integer(), nullable=True),
    sa.Column('gm_penalties', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_rank', sa.Integer(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('goals_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_per_game', sa.Float(), nullable=True),
    sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('total_in_rank', sa.Integer(), nullable=True),
    sa.Column('current_point_streak', sa.Integer(), nullable=True),
    sa.Column('current_point_streak_rank', sa.Integer(), nullable=True),
    sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True),
    sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('last_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'division_id', name='_team_division_uc_skater_team1')
    )
    with op.batch_alter_table('division_stats_skater_team', schema=None) as batch_op:
        batch_op.create_index('idx_division_team_assists_per_game', ['division_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_division_team_goals_per_game', ['division_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_division_team_points_per_game', ['division_id', 'points_per_game'], unique=False)
        batch_op.create_index('idx_division_team_team_id', ['team_id'], unique=False)

    op.create_table('org_stats_goalie_team',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_rank', sa.Integer(), nullable=True),
    sa.Column('games_participated', sa.Integer(), nullable=True),
    sa.Column('games_participated_rank', sa.Integer(), nullable=True),
    sa.Column('games_with_stats', sa.Integer(), nullable=True),
    sa.Column('games_with_stats_rank', sa.Integer(), nullable=True),
    sa.Column('goals_allowed', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_rank', sa.Integer(), nullable=True),
    sa.Column('goals_allowed_per_game', sa.Float(), nullable=True),
    sa.Column('goals_allowed_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('shots_faced', sa.Integer(), nullable=True),
    sa.Column('shots_faced_rank', sa.Integer(), nullable=True),
    sa.Column('save_percentage', sa.Float(), nullable=True),
    sa.Column('save_percentage_rank', sa.Integer(), nullable=True),
    sa.Column('total_in_rank', sa.Integer(), nullable=True),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('last_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'org_id', name='_team_org_uc_goalie_team1')
    )
    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.create_index('idx_org_team_goalie_gaa', ['org_id', 'goals_allowed_per_game'], unique=False)
        batch_op.create_index('idx_org_team_goalie_save_pct', ['org_id', 'save_percentage'], unique=False)
        batch_op.create_index('idx_org_team_goalie_team_id', ['team_id'], unique=False)

    op.create_table('org_stats_skater_team',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_played_rank', sa.Integer(), nullable=True),
    sa.Column('games_participated', sa.Integer(), nullable=True),
    sa.Column('games_participated_rank', sa.Integer(), nullable=True),
    sa.Column('games_with_stats', sa.Integer(), nullable=True),
    sa.Column('games_with_stats_rank', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('goals_rank', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('assists_rank', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('points_rank', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('penalties_rank', sa.Integer(), nullable=True),
    sa.Column('gm_penalties', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_rank', sa.Integer(), nullable=True),
    sa.Column('goals_per_game', sa.Float(), nullable=True),
    sa.Column('goals_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('points_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('penalties_per_game', sa.Float(), nullable=True),
    sa.Column('penalties_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('gm_penalties_per_game', sa.Float(), nullable=True),
    sa.Column('gm_penalties_per_game_rank', sa.Integer(), nullable=True),
    sa.Column('total_in_rank', sa.Integer(), nullable=True),
    sa.Column('current_point_streak', sa.Integer(), nullable=True),
    sa.Column('current_point_streak_rank', sa.Integer(), nullable=True),
    sa.Column('current_point_streak_avg_points', sa.Float(), nullable=True),
    sa.Column('current_point_streak_avg_points_rank', sa.Integer(), nullable=True),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('last_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['last_game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'org_id', name='_team_org_uc_skater_team1')
    )
    with op.batch_alter_table('org_stats_skater_team', schema=None) as batch_op:
        batch_op.create_index('idx_org_team_assists_per_game', ['org_id', 'assists_per_game'], unique=False)
        batch_op.create_index('idx_org_team_goals_per_game', ['org_id', 'goals_per_game'], unique=False)
        batch_op.create_index('idx_org_team_points_per_game', ['org_id', 'points_per_game'], unique=False)
        batch_op.create_index('idx_org_team_team_id', ['team_id'], unique=False)

    with op.batch_alter_table('human_embeddings', schema=None) as batch_op:
        batch_op.drop_index('idx_human_embeddings_vector', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('team_embeddings', schema=None) as batch_op:
        batch_op.drop_index('idx_team_embeddings_vector', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_embeddings', schema=None) as batch_op:
        batch_op.create_index('idx_team_embeddings_vector', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('human_embeddings', schema=None) as batch_op:
        batch_op.create_index('idx_human_embeddings_vector', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('org_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_index('idx_org_team_team_id')
        batch_op.drop_index('idx_org_team_points_per_game')
        batch_op.drop_index('idx_org_team_goals_per_game')
        batch_op.drop_index('idx_org_team_assists_per_game')

    op.drop_table('org_stats_skater_team')
    with op.batch_alter_table('org_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_index('idx_org_team_goalie_team_id')
        batch_op.drop_index('idx_org_team_goalie_save_pct')
        batch_op.drop_index('idx_org_team_goalie_gaa')

    op.drop_table('org_stats_goalie_team')
    with op.batch_alter_table('division_stats_skater_team', schema=None) as batch_op:
        batch_op.drop_index('idx_division_team_team_id')
        batch_op.drop_index('idx_division_team_points_per_game')
        batch_op.drop_index('idx_division_team_goals_per_game')
        batch_op.drop_index('idx_division_team_assists_per_game')

    op.drop_table('division_stats_skater_team')
    with op.batch_alter_table('division_stats_goalie_team', schema=None) as batch_op:
        batch_op.drop_index('idx_division_team_goalie_team_id')
        batch_op.drop_index('idx_division_team_goalie_save_pct')
        batch_op.drop_index('idx_division_team_goalie_gaa')

    op.drop_table('division_stats_goalie_team')
    # ### end Alembic commands ###
