"""new tabes s2s

Revision ID: bbb48c317afc
Revises: 7eb05b15d6df
Create Date: 2025-07-11 15:20:20.098070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb48c317afc'
down_revision = '7eb05b15d6df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skater_to_skater_stats_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_run_timestamp', sa.DateTime(), nullable=True),
    sa.Column('last_processed_game_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skater_to_skater_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skater1_id', sa.Integer(), nullable=False),
    sa.Column('skater2_id', sa.Integer(), nullable=False),
    sa.Column('games_against', sa.Integer(), nullable=False),
    sa.Column('games_tied_against', sa.Integer(), nullable=False),
    sa.Column('skater1_wins_vs_skater2', sa.Integer(), nullable=False),
    sa.Column('skater2_wins_vs_skater1', sa.Integer(), nullable=False),
    sa.Column('skater1_goals_against_skater2', sa.Integer(), nullable=False),
    sa.Column('skater2_goals_against_skater1', sa.Integer(), nullable=False),
    sa.Column('skater1_assists_against_skater2', sa.Integer(), nullable=False),
    sa.Column('skater2_assists_against_skater1', sa.Integer(), nullable=False),
    sa.Column('skater1_penalties_against_skater2', sa.Integer(), nullable=False),
    sa.Column('skater2_penalties_against_skater1', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skater1_id'], ['humans.id'], ),
    sa.ForeignKeyConstraint(['skater2_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skater1_id', 'skater2_id', name='_s2s_skater_pair_uc')
    )
    with op.batch_alter_table('skater_to_skater_stats', schema=None) as batch_op:
        batch_op.create_index('ix_s2s_skater_pair', ['skater1_id', 'skater2_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skater_to_skater_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_s2s_skater_pair')

    op.drop_table('skater_to_skater_stats')
    op.drop_table('skater_to_skater_stats_meta')
    # ### end Alembic commands ###
