"""Add home_ot_score and visitor_ot_score fields to Game model

Revision ID: cdf084f40be3
Revises: fe6f4ea45aef
Create Date: 2025-09-16 23:00:06.523864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf084f40be3'
down_revision = 'fe6f4ea45aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_ot_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visitor_ot_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('visitor_ot_score')
        batch_op.drop_column('home_ot_score')

    # ### end Alembic commands ###
