"""Add level_id to per-game stats tables

Revision ID: d19d57770097
Revises: 13680bb09319
Create Date: 2025-11-18 21:52:22.915817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd19d57770097'
down_revision = '13680bb09319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_game_stats_goalie_level_id'), ['level_id'], unique=False)
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])

    with op.batch_alter_table('game_stats_skater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_game_stats_skater_level_id'), ['level_id'], unique=False)
        batch_op.create_foreign_key(None, 'levels', ['level_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats_skater', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_stats_skater_level_id'))
        batch_op.drop_column('level_id')

    with op.batch_alter_table('game_stats_goalie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_stats_goalie_level_id'))
        batch_op.drop_column('level_id')

    # ### end Alembic commands ###
