"""Add skill_id to Division and move skill_propagation_sequence, skill_value  to Skill

Revision ID: efebc8e5d2a3
Revises: 929f87c61fa3
Create Date: 2025-01-29 16:48:55.533808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efebc8e5d2a3'
down_revision = '929f87c61fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['id'])
        batch_op.drop_column('skill_value')
        batch_op.drop_column('skill_propagation_sequence')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_propagation_sequence', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('skill_propagation_sequence')

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_propagation_sequence', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('skill_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skill_id')

    # ### end Alembic commands ###
