"""Add n_games field to SkillValuePPGRatio

Revision ID: f3facb0580dd
Revises: 10ca37ca3956
Create Date: 2025-01-30 10:30:43.985931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3facb0580dd'
down_revision = '10ca37ca3956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels_graph_edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_games', sa.Integer(), nullable=False))

    with op.batch_alter_table('skill_value_ppg_ratios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_games', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_value_ppg_ratios', schema=None) as batch_op:
        batch_op.drop_column('n_games')

    with op.batch_alter_table('levels_graph_edges', schema=None) as batch_op:
        batch_op.drop_column('n_games')

    # ### end Alembic commands ###
