"""Alter Location table: add location_name, remove org_id

Revision ID: f7a04b6be8b9
Revises: f3d8cf5936fa
Create Date: 2025-11-25 18:18:02.158320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a04b6be8b9'
down_revision = 'f3d8cf5936fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=200), nullable=False))
        batch_op.drop_constraint('_org_rink_name_uc', type_='unique')
        batch_op.create_unique_constraint('_location_rink_name_uc', ['location_name', 'rink_name'])
        batch_op.drop_constraint('locations_org_id_fkey', type_='foreignkey')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('locations_org_id_fkey', 'organizations', ['org_id'], ['id'])
        batch_op.drop_constraint('_location_rink_name_uc', type_='unique')
        batch_op.create_unique_constraint('_org_rink_name_uc', ['org_id', 'rink_name'])
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
