"""Add GoalieSaves and ScorekeeperSaveQuality tables with JSONB saves_timestamps field

Revision ID: fe6f4ea45aef
Revises: 2fe072baf4ba
Create Date: 2025-09-10 17:01:04.838627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6f4ea45aef'
down_revision = '2fe072baf4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goalie_saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('goalie_id', sa.Integer(), nullable=False),
    sa.Column('saves_count', sa.Integer(), nullable=False),
    sa.Column('shots_against', sa.Integer(), nullable=False),
    sa.Column('goals_allowed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['goalie_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'goalie_id', name='_game_goalie_saves_uc')
    )
    op.create_table('scorekeeper_save_quality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('scorekeeper_id', sa.Integer(), nullable=False),
    sa.Column('total_saves_recorded', sa.Integer(), nullable=False),
    sa.Column('max_saves_per_5sec', sa.Integer(), nullable=False),
    sa.Column('max_saves_per_20sec', sa.Integer(), nullable=False),
    sa.Column('saves_timestamps', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['scorekeeper_id'], ['humans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'scorekeeper_id', name='_game_scorekeeper_quality_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorekeeper_save_quality')
    op.drop_table('goalie_saves')
    # ### end Alembic commands ###
